# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the Spring Boot app into the container
COPY . /app

# Expose the port the app runs on (8080 is default for Spring Boot)
EXPOSE 8080

# Build and run the Spring Boot application
CMD ["java", "-jar", "target/Udaan-0.0.1-SNAPSHOT.jar"]
