version: '3'

services:
  backend:
    build:
      context: ./LMS_Backend    # Set the context to the backend folder
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./udaan_frontend  # Set the context to the frontend folder
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
